const usersToSeed = [
  {
    userId: "admin01",
    name: "Admin User",
    email: "admin@pnc.edu.ph",
    password: "password123",
    role: "admin",
    accountStatus: "active",
  },
  {
    userId: "faculty01",
    name: "Maria Santos",
    email: "maria.santos@pnc.edu.ph",
    password: "password123",
    role: "faculty",
    accountStatus: "active",
  },
  {
    userId: "faculty02",
    name: "Juan Reyes",
    email: "juan.reyes@pnc.edu.ph",
    password: "password123",
    role: "faculty",
    accountStatus: "active",
  },
  {
    userId: "student01",
    name: "Carl Lawrence Antioquia",
    email: "carl.antioquia@pnc.edu.ph",
    password: "password123",
    role: "student",
    accountStatus: "active",
  },
  {
    userId: "student02",
    name: "Lemuel John Ellasus",
    email: "lemuel.ellasus@pnc.edu.ph",
    password: "password123",
    role: "student",
    accountStatus: "active",
  },
];

const adminProfilesToSeed = [
  {
    userId: "admin01",
    fullName: "Admin User",
    position: "System Administrator",
    contactNumber: "09171112222",
    achievements: "System Uptime 99.9%",
    skills: "System Administration, Security, DevOps",
    interests: "Infrastructure, Automation",
  },
];

const facultyProfilesToSeed = [
  {
    userId: "faculty01",
    employeeIdNumber: "EMP-2020-001",
    firstName: "Maria",
    middleName: "L.",
    lastName: "Santos",
    gender: "Female",
    department: "IT",
    position: "Instructor",
    contactNumber: "09189876543",
    achievements: "Best Instructor 2024",
    skills: "Python, Web Development, Database Design",
    interests: "Curriculum Development, AI",
  },
  {
    userId: "faculty02",
    employeeIdNumber: "EMP-2018-042",
    firstName: "Juan",
    middleName: "R.",
    lastName: "Reyes",
    gender: "Male",
    department: "CS",
    position: "Associate Professor",
    contactNumber: "09191112222",
    achievements: "Research Publication Award",
    skills: "Algorithms, Machine Learning, Data Science",
    interests: "Research, Optimization",
  },
];

const studentProfilesToSeed = [
  {
    userId: "student01",
    studentNumber: "2023-0001",
    firstName: "Carl Lawrence",
    middleName: "",
    lastName: "Antioquia",
    gender: "Male",
    yearLevel: "4th Year",
    program: "BSIT",
    academicStatus: "regular",
    height: 170,
    weight: 65,
    contactNumber: "09171112222",
    emergencyContactName: "Maria Antioquia",
    emergencyContactNumber: "09181112222",
    emergencyContactRelation: "Mother",
    achievements: "Dean's Lister (2023)",
    skills: "Java, Python, C++",
    interests: "Software Development",
  },
  {
    userId: "student02",
    studentNumber: "2023-0002",
    firstName: "Lemuel John",
    middleName: "O.",
    lastName: "Ellasus",
    gender: "Male",
    yearLevel: "4th Year",
    program: "BSIT",
    academicStatus: "regular",
    height: 168,
    weight: 62,
    contactNumber: "09172223333",
    emergencyContactName: "Susan Ellasus",
    emergencyContactNumber: "09182223333",
    emergencyContactRelation: "Mother",
    achievements: "Hackathon Finalist",
    skills: "Python, R, Machine Learning",
    interests: "Data Analytics, AI",
  },
];

const coursesToSeed = [
  { code: "CCS101", desc: "Introduction to Computing", units: 3, prereq: "--", year: 1, sem: 1 },
  { code: "CCS102", desc: "Computer Programming 1", units: 3, prereq: "--", year: 1, sem: 1 },
  { code: "ETH101", desc: "Ethics", units: 3, prereq: "--", year: 1, sem: 1 },
  { code: "MAT101", desc: "Mathematics in the Modern World", units: 3, prereq: "--", year: 1, sem: 1 },
  { code: "NSTP1", desc: "National Service Training Program 1", units: 3, prereq: "--", year: 1, sem: 1 },
  { code: "PED101", desc: "Physical Education 1", units: 2, prereq: "--", year: 1, sem: 1 },
  { code: "PSY100", desc: "Understanding the Self", units: 3, prereq: "--", year: 1, sem: 1 },
  { code: "CCS103", desc: "Computer Programming 2", units: 3, prereq: "CCS102", year: 1, sem: 2 },
  { code: "CCS104", desc: "Discrete Structures 1", units: 3, prereq: "MAT101", year: 1, sem: 2 },
  { code: "CCS105", desc: "Human Computer Interaction 1", units: 3, prereq: "CCS101", year: 1, sem: 2 },
  { code: "CCS106", desc: "Social and Professional Issues", units: 3, prereq: "ETH101", year: 1, sem: 2 },
  { code: "COM101", desc: "Purposive Communication", units: 3, prereq: "--", year: 1, sem: 2 },
  { code: "GAD101", desc: "Gender and Development", units: 3, prereq: "--", year: 1, sem: 2 },
  { code: "NSTP2", desc: "National Service Training Program 2", units: 3, prereq: "NSTP1", year: 1, sem: 2 },
  { code: "PED102", desc: "Physical Education 2", units: 2, prereq: "PED101", year: 1, sem: 2 },
];

module.exports = {
  usersToSeed,
  adminProfilesToSeed,
  facultyProfilesToSeed,
  studentProfilesToSeed,
  coursesToSeed,
};